---
name: Java_CI_Gradle

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build

    - name: Lint with Gradle
      run: ./gradlew lint --status
    
    - name: Test with Gradle
      run: ./gradlew test

    - name: About directory
      run: pwd && ls -l

    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: BudgetFy apk
        path: /home/runner/work/BudgetFy/BudgetFy/app/build/outputs/apk/debug/app-debug.apk
